### PR TITLE
Update nbextensions notebook from @nbollweg

### PR DESCRIPTION
**Pull request by willingc**
@ellisonbg Opening this as a PR against your branch.

### CODE REVIEW

**Comment by ellisonbg** [comment]
I think you branched off master, rather than my branch as there are a lot
of commits from master in your PR. @jdfreder should I rebase this on master?

On Mon, Mar 14, 2016 at 11:56 AM, Carol Willing notifications@github.com
wrote:

> @ellisonbg https://github.com/ellisonbg Opening this as a PR against
> 
> ## your branch.
> 
> You can view, comment on, or merge this pull request online at:
> 
>   https://github.com/ellisonbg/notebook/pull/14
> Commit Summary
> - don't concatenate stream outputs larger than 8k
> - Implement markdown cell attachments. Allow drag’n’drop of images
>   into markdown cells. See #613
> - Use the cell ‘attachments’ property instead of
>   ‘metadata.attachments’.
> - Insert markdown markup for attachments images instead of HTML
> - Add attachments cell toolbar option which opens a metadata-like JSON
>   editor.
> - Keep the attachments even if the cell type changes
> - Refactor the inline image drop logic. Preliminary copy/paste support.
> - Add a new insert-image action and corresponding dialog to insert
>   inline images from menu.
> - Nicer attachments editing dialog
> - Attachments dialog only apply deletion on ‘Apply’.
> - Fix drag/drop event handler to be compatible with codemirror 5.8,
>   which
> - Check that we have items in markdown cell paste handler
> - Add Cut/Copy/Paste Cell attachments menu items
> - Add tests for attachments insert menuitem
> - Fix speed issues when attaching large images
> - Fix 'insert-image' menu item toggling. Instead of disabling the
>   menuitem in unselect, we preventively disable it in Cell.select and let
>   cell subtypes re-enable it when needed.
> - Make attachments textcell-specific
> - Bump nbformat minor to 4.1 to support attachments
> - Fix cell attachments copy/paste
> - Simplify attachments handling code by having an attachment attribute
>   in every cell
> - Remove unused attachments on manual save
> - Explain why we disable caja uri checks on img::src
> - Exempt javascript files from files check
> - Remove jquery from dependencies since it’s a global
> - Add Copy/Paste cell attachments test
> - Add test for attachments garbage collection
> - Add dependencies to python build layer
> - Merge pull request #1143 from captainsafia/fix-edit-for-js
> - Add comment to line 5 referencing docker-stacks
> - Merge pull request #1149 from dsifford/patch-1
> - Update to latest plugins
> - Merge pull request #1153 from blink1073/update-plugins
> - Add about page
> - Merge pull request #1165 from blink1073/lab-about-page
> - allow notebook-dir to be root
> - Merge pull request #1168 from minrk/allow-root-notebook-dir
> - Dockerfile: Add missing `--no-cache-dir` option.
> - Merge pull request #1172 from jakirkham/minor_docker_opts
> - Adjust styling of dropdown header in new menu
> - Adjust text of notebook heading in new menu
> - Merge pull request #621 from julienr/inline_images
> - Merge pull request #506 from minrk/limit-output
> - add missing url-encoding of base_url in terminal/edit templates
> - Merge pull request #1187 from minrk/encode-url-terminal
> - Merge pull request #1180 from takluyver/new-notebook-menu-header
> - Merge branch 'nbext-pain' of https://github.com/ellisonbg/notebook
>   into update-nb
> - Edit documentation notebook
> - Fix @nbollweg comments
> 
> File Changes
> - _M_ Dockerfile
>   https://github.com/ellisonbg/notebook/pull/14/files#diff-0 (7)
> - _M_ docs/source/examples/Notebook/Distributing Jupyter Extensions as
>   Python Packages.ipynb
>   https://github.com/ellisonbg/notebook/pull/14/files#diff-1 (105)
> - _M_ notebook/notebookapp.py
>   https://github.com/ellisonbg/notebook/pull/14/files#diff-2 (5)
> - _M_ notebook/static/base/js/dialog.js
>   https://github.com/ellisonbg/notebook/pull/14/files#diff-3 (177)
> - _M_ notebook/static/base/js/security.js
>   https://github.com/ellisonbg/notebook/pull/14/files#diff-4 (6)
> - _M_ notebook/static/base/js/utils.js
>   https://github.com/ellisonbg/notebook/pull/14/files#diff-5 (22)
> - _M_ notebook/static/lab/index.js
>   https://github.com/ellisonbg/notebook/pull/14/files#diff-6 (3)
> - _M_ notebook/static/lab/package.json
>   https://github.com/ellisonbg/notebook/pull/14/files#diff-7 (2)
> - _M_ notebook/static/notebook/js/actions.js
>   https://github.com/ellisonbg/notebook/pull/14/files#diff-8 (28)
> - _M_ notebook/static/notebook/js/cell.js
>   https://github.com/ellisonbg/notebook/pull/14/files#diff-9 (27)
> - _A_ notebook/static/notebook/js/celltoolbarpresets/attachments.js
>   https://github.com/ellisonbg/notebook/pull/14/files#diff-10 (50)
> - _M_ notebook/static/notebook/js/codecell.js
>   https://github.com/ellisonbg/notebook/pull/14/files#diff-11 (10)
> - _M_ notebook/static/notebook/js/menubar.js
>   https://github.com/ellisonbg/notebook/pull/14/files#diff-12 (4)
> - _M_ notebook/static/notebook/js/notebook.js
>   https://github.com/ellisonbg/notebook/pull/14/files#diff-13 (151)
> - _M_ notebook/static/notebook/js/outputarea.js
>   https://github.com/ellisonbg/notebook/pull/14/files#diff-14 (56)
> - _M_ notebook/static/notebook/js/textcell.js
>   https://github.com/ellisonbg/notebook/pull/14/files#diff-15 (174)
> - _M_ notebook/static/tree/js/notebooklist.js
>   https://github.com/ellisonbg/notebook/pull/14/files#diff-16 (1)
> - _M_ notebook/static/tree/less/tree.less
>   https://github.com/ellisonbg/notebook/pull/14/files#diff-17 (7)
> - _M_ notebook/templates/edit.html
>   https://github.com/ellisonbg/notebook/pull/14/files#diff-18 (2)
> - _M_ notebook/templates/notebook.html
>   https://github.com/ellisonbg/notebook/pull/14/files#diff-19 (6)
> - _M_ notebook/templates/terminal.html
>   https://github.com/ellisonbg/notebook/pull/14/files#diff-20 (2)
> - _M_ notebook/templates/tree.html
>   https://github.com/ellisonbg/notebook/pull/14/files#diff-21 (2)
> - _A_ notebook/tests/_testdata/black_square_22.png
>   https://github.com/ellisonbg/notebook/pull/14/files#diff-22 (0)
> - _A_ notebook/tests/notebook/attachments.js
>   https://github.com/ellisonbg/notebook/pull/14/files#diff-23 (123)
> - _M_ notebook/tests/test_notebookapp.py
>   https://github.com/ellisonbg/notebook/pull/14/files#diff-24 (5)
> 
> Patch Links:
> - https://github.com/ellisonbg/notebook/pull/14.patch
> - https://github.com/ellisonbg/notebook/pull/14.diff
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/ellisonbg/notebook/pull/14.

## 

Brian E. Granger
Associate Professor of Physics and Data Science
Cal Poly State University, San Luis Obispo
@ellisonbg on Twitter and GitHub
bgranger@calpoly.edu and ellisonbg@gmail.com

**Comment by willingc** [comment]
I could cherry pick the last two commits and that should work as well since I only edited the one notebook.

**Comment by willingc** [comment]
@ellisonbg This is probably more useful now ;-)

**Comment by jdfreder** [comment]
Thanks @willingc !

**Comment by willingc** [comment]
Thanks @jdfreder and @ellisonbg.

**Pull request merged**
