### PR TITLE
Add command template for nbextension enable after install

### PR DESCRIPTION
**Pull request by bollwyvl**
> Answers https://github.com/jupyter/notebook/pull/879#issuecomment-193404634

Here's some sample output:

``` shell
nbollweg@rocinante:~/Documents/projects/notebook (nbext-pain-install-msg)$ jupyter nbextension install --py nbpresent --sys-prefix --overwrite --symlink
Unrecognized JSON config file version, assuming version 1
Installing /Users/nbollweg/Documents/projects/nbpresent/nbpresent/static/nbpresent -> nbpresent
Removing: /Users/nbollweg/miniconda/envs/nbpresent42/share/jupyter/nbextensions/nbpresent
Symlinking: /Users/nbollweg/miniconda/envs/nbpresent42/share/jupyter/nbextensions/nbpresent -> /Users/nbollweg/Documents/projects/nbpresent/nbpresent/static/nbpresent
- Validating: OK

    To initialize this nbextension in the browser every time the notebook (or other app) loads:

          jupyter nbextension enable nbpresent --py --sys-prefix
```

If not using `--py`, the templated command is not as good:

``` shell
nbollweg@rocinante:~/Documents/projects/notebook (nbext-pain-install-msg)$ jupyter nbextension install /Users/nbollweg/Documents/projects/nbpresent/nbpresent/static/nbpresent --sys-prefix --overwrite --symlink
Unrecognized JSON config file version, assuming version 1
Removing: /Users/nbollweg/miniconda/envs/nbpresent42/share/jupyter/nbextensions/nbpresent
Symlinking: /Users/nbollweg/miniconda/envs/nbpresent42/share/jupyter/nbextensions/nbpresent -> /Users/nbollweg/Documents/projects/nbpresent/nbpresent/static/nbpresent

    To initialize this nbextension in the browser every time the notebook (or other app) loads:

          jupyter nbextension enable <the entry point> --sys-prefix
```

I suppose we _could_ grep for the magic name to find the entrypoint, but that seems error-prone: i.e. if you have more than one extension in a single folder, etc.

### CODE REVIEW

**Comment by bollwyvl** [comment]
Note that we can't validate an unpackaged `nbextension install` for the same reason. 

> Blargh, it would be nice to adopt index.js (or notebook|tree|common.js)

**Comment by Carreau** [comment]
+1, thanks a lot (sorry don't have right to merge)

**Comment by bollwyvl** [comment]
> +1, thanks a lot (sorry don't have right to merge) 

s'okay... more  :eyes:  good!

**Comment by jdfreder** [comment]
Thanks!

**Pull request merged**
